- chosic: 
    base_url: https://www.chosic.com/free-music/{tags}
    tags:
      - Ambient
      - Classical
      - Cinematic
      - Electronic
      - Folk
      - Funk
      - Hip-Hop
      - Jazz
      - Pop
      - Rock
      - Soul
      - Blues
      - Country
      - Reggae
      - Latin
      - Metal
      - Dance
      - Chill
      - Acoustic
      - Instrumental
      - Lo-fi
      - Happy
      - Sad
      - Relaxing
      - Upbeat
      - Motivational
      - Funny
      - Dramatic
      - Romantic
      - Horror
      - Epic
      - Corporate
      - Kids
      - Holiday
      - Sound Effects
      - Nature
      - Space
      - Sci-fi
      - Fantasy
      - Historical
      - Adventure
      - Action
      - Mystery
      - Suspense
      - Thriller
      - Comedy
      - Documentary
      - Travel
      - Sports
      - News
      - Games
      - Workout
      - Meditation
      - Study
      - Sleep
      - Background
      - Wedding
      - Party
