import reflex as rx

def homepage():
    return rx.fragment(
        rx.el.link(
            rel="preload",
            href="/_next/static/media/a34f9d1faa5f3315-s.p.woff2",
            as_="font",
            crossorigin=True,
            type="font/woff2",
        ),
        rx.el.link(
            rel="preload", as_="image", href="https://i.ibb.co/m9ywqcs/Joe-Rogan.png"
        ),
        rx.el.link(
            rel="preload", as_="image", href="https://i.ibb.co/HFZ6VvW/Andrew-Huberman.png"
        ),
        rx.el.link(
            rel="preload",
            as_="image",
            href="https://i.ibb.co/MPJWNZQ/Sam-Harris-Cartoon.png",
        ),
        rx.el.link(
            rel="preload",
            as_="image",
            href="https://replicate.delivery/pbxt/QjGtucx4kAKBPxi4UwAOTTVteSJmezbq40k7NDwo5w16jjDTA/ComfyUI_00002_.png",
        ),
        rx.el.link(
            rel="preload",
            as_="image",
            href="https://replicate.delivery/pbxt/t2T7oFjCUcbgOpFplfckt3Tb7fOvQ0f88clfEwPXNOMvyUOMB/ComfyUI_00002_.png",
        ),
        rx.el.link(
            rel="preload",
            as_="image",
            href="https://replicate.delivery/pbxt/CEBtzXHIOT7VDtPHeBXwAJDlcwcZ4cM42tuJ4A7zTMP1zxhJA/ComfyUI_00002_.png",
        ),
        rx.el.link(
            rel="preload",
            as_="image",
            href="https://replicate.delivery/pbxt/eboohJoDnOTvJ62MOZzsVnNJJDyOAe1cp4mYwlcQ2nxHPlDTA/ComfyUI_00002_.png",
        ),
        rx.el.link(
            rel="preload",
            as_="image",
            href="https://replicate.delivery/pbxt/BtneAyluBHUPHqZ9NFauyH5P65Fkwuf3LbvAUjfZ0be9HVOMB/ComfyUI_00002_.png",
        ),
        rx.el.link(
            rel="preload",
            as_="image",
            href="https://replicate.delivery/pbxt/ZtJM15tz4n6nGpZkZ2bi6yLTfi4MGE3emyLHAUXir1JoUlDTA/ComfyUI_00002_.png",
        ),
        rx.el.link(
            rel="preload",
            as_="image",
            href="https://replicate.delivery/pbxt/zxT3wXAdPE6rNJP1sfroJiTawHskstDIJyX2ufD4fXaw8LHmA/ComfyUI_00002_.png",
        ),
        rx.el.link(
            rel="stylesheet",
            href="/_next/static/css/628765f20b848f76.css",
            custom_attrs={"data-precedence": "next"},
        ),
        rx.el.link(
            rel="stylesheet",
            href="/_next/static/css/50eff5b5a304083f.css",
            custom_attrs={"data-precedence": "next"},
        ),
        rx.el.link(
            rel="preload",
            as_="script",
            fetchpriority="low",
            href="/_next/static/chunks/webpack-cc0e97d36042a1cd.js",
        ),
        rx.script(
            src="/_next/static/chunks/fd9d1056-90960e0a7e77703c.js",
            strategy="afterInteractive",
        ),
        rx.script(
            src="/_next/static/chunks/23-64c51ed18d654881.js", strategy="afterInteractive"
        ),
        rx.script(
            src="/_next/static/chunks/main-app-f73cdb3bce740b12.js",
            strategy="afterInteractive",
        ),
        rx.script(
            src="/_next/static/chunks/8e1d74a4-44c6c3343a88bc09.js",
            strategy="afterInteractive",
        ),
        rx.script(
            src="/_next/static/chunks/740-c96163b104825a35.js", strategy="afterInteractive"
        ),
        rx.script(
            src="/_next/static/chunks/app/page-4ac0b61589c3b625.js",
            strategy="afterInteractive",
        ),
        rx.script(
            src="/_next/static/chunks/aa7babf8-d144d7c22dac3895.js",
            strategy="afterInteractive",
        ),
        rx.script(
            src="/_next/static/chunks/644-a8d8bdbd19f2f51f.js", strategy="afterInteractive"
        ),
        rx.script(
            src="/_next/static/chunks/138-632539dc9da923bc.js", strategy="afterInteractive"
        ),
        rx.script(
            src="/_next/static/chunks/444-6f20abd6757d460c.js", strategy="afterInteractive"
        ),
        rx.script(
            src="/_next/static/chunks/app/layout-fc81a75f4f9d4044.js",
            strategy="afterInteractive",
        ),
        rx.el.link(
            rel="preload", as_="image", href="https://i.ibb.co/4Mw6Htt/Jensen-Huang.png"
        ),
        rx.el.link(
            rel="preload",
            as_="image",
            href="https://replicate.delivery/pbxt/eN4pHz2D49XAYqPxnaFcZolYxGzEcdlmpBk5cen8Ib7fFMHmA/ComfyUI_00002_.png",
        ),
        rx.el.link(
            rel="preload",
            as_="image",
            href="https://i.ibb.co/hmY3sd8/pikaso-texttoimage-Cartoon-closeup-portrait-of-presidential-candidate-removebg-preview-transformed.png",
        ),
        rx.el.link(
            rel="preload",
            as_="image",
            href="https://replicate.delivery/pbxt/EwtmumDFmBoxMB6vF207UslR2vZmHoLUPnWffBkizfGXYPHmA/ComfyUI_00002_.png",
        ),
        rx.el.link(
            rel="preload",
            as_="image",
            href="https://i.ibb.co/PTHQ7Qn/modi-indianprimeminister-removebg.png",
        ),
        rx.el.link(
            rel="preload", as_="image", href="https://i.ibb.co/qymPbXp/Angela-Markel.png"
        ),
        rx.el.link(
            rel="preload",
            as_="image",
            href="https://i.ibb.co/wJR6HTJ/Megan-Thee-Stallion.png",
        ),
        rx.el.link(
            rel="preload", as_="image", href="https://i.ibb.co/p0mydmw/Neil-Tyson.png"
        ),
        rx.el.link(
            rel="preload",
            as_="image",
            href="https://www.shutterstock.com/image-vector/user-profile-icon-vector-avatar-600nw-2220431045.jpg",
        ),
        rx.el.link(rel="icon", href="/favicon.ico"),
        rx.script(
            src="/_next/static/chunks/polyfills-42372ed130431b0a.js",
            custom_attrs={"nomodule": True},
        ),
        rx.box(
            rx.script(
                """!function(){try{var d=document.documentElement,c=d.classList;c.remove('light','dark');var e=localStorage.getItem('theme');if('system'===e||(!e&&true)){var t='(prefers-color-scheme: dark)',m=window.matchMedia(t);if(m.media!==t||m.matches){d.style.colorScheme = 'dark';c.add('dark')}else{d.style.colorScheme = 'light';c.add('light')}}else if(e){c.add(e|| '')}if(e==='light'||e==='dark')d.style.colorScheme=e}catch(e){}}()"""
            ),
            rx.box(
                rx.flex(
                    rx.el.template(
                        custom_attrs={"data-dgst": "BAILOUT_TO_CLIENT_SIDE_RENDERING"}
                    ),
                    rx.box(
                        rx.flex(
                            rx.flex(
                                rx.box(
                                    rx.box(
                                        rx.heading(
                                            "FiCast Fantasy Podcast",
                                            font_weight="800",
                                            font_size="3.75rem",
                                            line_height="1",
                                            as_="h1",
                                        ),
                                        rx.heading(
                                            "Thoughtful Podcasts Prepared with AI-driven Research for AI Characters",
                                            margin_top="2rem",
                                            font_size="1.25rem",
                                            line_height="1.75rem",
                                            as_="h2",
                                        ),
                                        rx.text(
                                            "Instructions: Select at least one host and one guest.",
                                            font_style="italic",
                                            margin_top="1rem",
                                            font_size="1.125rem",
                                            line_height="1.75rem",
                                        ),
                                        text_align="center",
                                    ),
                                    rx.box(
                                        rx.heading(
                                            "Hosts",
                                            font_weight="700",
                                            margin_bottom="1rem",
                                            margin_top="2rem",
                                            font_size="1.25rem",
                                            line_height="1.75rem",
                                            as_="h2",
                                        ),
                                        rx.box(
                                            rx.el.button(
                                                rx.flex(
                                                    rx.image(
                                                        src="https://i.ibb.co/m9ywqcs/Joe-Rogan.png",
                                                        alt="Joe Rogan",
                                                        max_width="100%",
                                                        max_height="100%",
                                                        object_fit="contain",
                                                        border_radius="0.5rem",
                                                    ),
                                                    display="flex",
                                                    height="10rem",
                                                    align_items="center",
                                                    justify_content="center",
                                                    width="10rem",
                                                ),
                                                rx.el.br(),
                                                rx.text.span(
                                                    "Joe Rogan",
                                                    font_size="0.75rem",
                                                    line_height="1rem",
                                                ),
                                                class_name="dark:border-purple-700",
                                                background_color="transparent",
                                                border_width="2px",
                                                border_color="#1E3A8A",
                                                border_style="solid",
                                                display="flex",
                                                flex_direction="column",
                                                align_items="center",
                                                justify_content="center",
                                                padding="0.75rem",
                                                border_radius="1rem",
                                            ),
                                            rx.el.button(
                                                rx.flex(
                                                    rx.image(
                                                        src="https://i.ibb.co/HFZ6VvW/Andrew-Huberman.png",
                                                        alt="Andrew Huberman",
                                                        max_width="100%",
                                                        max_height="100%",
                                                        object_fit="contain",
                                                        border_radius="0.5rem",
                                                    ),
                                                    display="flex",
                                                    height="10rem",
                                                    align_items="center",
                                                    justify_content="center",
                                                    width="10rem",
                                                ),
                                                rx.el.br(),
                                                rx.text.span(
                                                    "Andrew Huberman",
                                                    font_size="0.75rem",
                                                    line_height="1rem",
                                                ),
                                                class_name="dark:border-purple-700",
                                                background_color="transparent",
                                                border_width="2px",
                                                border_color="#1E3A8A",
                                                border_style="solid",
                                                display="flex",
                                                flex_direction="column",
                                                align_items="center",
                                                justify_content="center",
                                                padding="0.75rem",
                                                border_radius="1rem",
                                            ),
                                            rx.el.button(
                                                rx.flex(
                                                    rx.image(
                                                        src="https://i.ibb.co/MPJWNZQ/Sam-Harris-Cartoon.png",
                                                        alt="Sam Harris",
                                                        max_width="100%",
                                                        max_height="100%",
                                                        object_fit="contain",
                                                        border_radius="0.5rem",
                                                    ),
                                                    display="flex",
                                                    height="10rem",
                                                    align_items="center",
                                                    justify_content="center",
                                                    width="10rem",
                                                ),
                                                rx.el.br(),
                                                rx.text.span(
                                                    "Sam Harris",
                                                    font_size="0.75rem",
                                                    line_height="1rem",
                                                ),
                                                class_name="dark:border-purple-700",
                                                background_color="transparent",
                                                border_width="2px",
                                                border_color="#1E3A8A",
                                                border_style="solid",
                                                display="flex",
                                                flex_direction="column",
                                                align_items="center",
                                                justify_content="center",
                                                padding="0.75rem",
                                                border_radius="1rem",
                                            ),
                                            gap="2rem",
                                            display="grid",
                                            grid_template_columns="repeat(3, minmax(0, 1fr))",
                                            margin_bottom="2rem",
                                        ),
                                        rx.heading(
                                            "Guests",
                                            font_weight="700",
                                            margin_bottom="1rem",
                                            margin_top="2rem",
                                            font_size="1.25rem",
                                            line_height="1.75rem",
                                            as_="h2",
                                        ),
                                        rx.box(
                                            rx.el.button(
                                                rx.flex(
                                                    rx.image(
                                                        src="https://replicate.delivery/pbxt/QjGtucx4kAKBPxi4UwAOTTVteSJmezbq40k7NDwo5w16jjDTA/ComfyUI_00002_.png",
                                                        alt="Harry Potter",
                                                        max_width="100%",
                                                        max_height="100%",
                                                        object_fit="contain",
                                                        border_radius="0.5rem",
                                                    ),
                                                    display="flex",
                                                    height="10rem",
                                                    align_items="center",
                                                    justify_content="center",
                                                    width="10rem",
                                                ),
                                                rx.el.br(),
                                                rx.text.span(
                                                    "Harry Potter",
                                                    font_size="0.75rem",
                                                    line_height="1rem",
                                                ),
                                                class_name="dark:border-purple-700",
                                                background_color="transparent",
                                                border_width="2px",
                                                border_color="#1E3A8A",
                                                border_style="solid",
                                                display="flex",
                                                flex_direction="column",
                                                align_items="center",
                                                justify_content="center",
                                                padding="0.75rem",
                                                border_radius="1rem",
                                            ),
                                            rx.el.button(
                                                rx.flex(
                                                    rx.image(
                                                        src="https://replicate.delivery/pbxt/t2T7oFjCUcbgOpFplfckt3Tb7fOvQ0f88clfEwPXNOMvyUOMB/ComfyUI_00002_.png",
                                                        alt="Iron Man",
                                                        max_width="100%",
                                                        max_height="100%",
                                                        object_fit="contain",
                                                        border_radius="0.5rem",
                                                    ),
                                                    display="flex",
                                                    height="10rem",
                                                    align_items="center",
                                                    justify_content="center",
                                                    width="10rem",
                                                ),
                                                rx.el.br(),
                                                rx.text.span(
                                                    "Iron Man",
                                                    font_size="0.75rem",
                                                    line_height="1rem",
                                                ),
                                                class_name="dark:border-purple-700",
                                                background_color="transparent",
                                                border_width="2px",
                                                border_color="#1E3A8A",
                                                border_style="solid",
                                                display="flex",
                                                flex_direction="column",
                                                align_items="center",
                                                justify_content="center",
                                                padding="0.75rem",
                                                border_radius="1rem",
                                            ),
                                            rx.el.button(
                                                rx.flex(
                                                    rx.image(
                                                        src="https://replicate.delivery/pbxt/CEBtzXHIOT7VDtPHeBXwAJDlcwcZ4cM42tuJ4A7zTMP1zxhJA/ComfyUI_00002_.png",
                                                        alt="Darth Vader",
                                                        max_width="100%",
                                                        max_height="100%",
                                                        object_fit="contain",
                                                        border_radius="0.5rem",
                                                    ),
                                                    display="flex",
                                                    height="10rem",
                                                    align_items="center",
                                                    justify_content="center",
                                                    width="10rem",
                                                ),
                                                rx.el.br(),
                                                rx.text.span(
                                                    "Darth Vader",
                                                    font_size="0.75rem",
                                                    line_height="1rem",
                                                ),
                                                class_name="dark:border-purple-700",
                                                background_color="transparent",
                                                border_width="2px",
                                                border_color="#1E3A8A",
                                                border_style="solid",
                                                display="flex",
                                                flex_direction="column",
                                                align_items="center",
                                                justify_content="center",
                                                padding="0.75rem",
                                                border_radius="1rem",
                                            ),
                                            rx.el.button(
                                                rx.flex(
                                                    rx.image(
                                                        src="https://replicate.delivery/pbxt/eboohJoDnOTvJ62MOZzsVnNJJDyOAe1cp4mYwlcQ2nxHPlDTA/ComfyUI_00002_.png",
                                                        alt="Alan Turing",
                                                        max_width="100%",
                                                        max_height="100%",
                                                        object_fit="contain",
                                                        border_radius="0.5rem",
                                                    ),
                                                    display="flex",
                                                    height="10rem",
                                                    align_items="center",
                                                    justify_content="center",
                                                    width="10rem",
                                                ),
                                                rx.el.br(),
                                                rx.text.span(
                                                    "Alan Turing",
                                                    font_size="0.75rem",
                                                    line_height="1rem",
                                                ),
                                                class_name="dark:border-purple-700",
                                                background_color="transparent",
                                                border_width="2px",
                                                border_color="#1E3A8A",
                                                border_style="solid",
                                                display="flex",
                                                flex_direction="column",
                                                align_items="center",
                                                justify_content="center",
                                                padding="0.75rem",
                                                border_radius="1rem",
                                            ),
                                            rx.el.button(
                                                rx.flex(
                                                    rx.image(
                                                        src="https://replicate.delivery/pbxt/BtneAyluBHUPHqZ9NFauyH5P65Fkwuf3LbvAUjfZ0be9HVOMB/ComfyUI_00002_.png",
                                                        alt="Albert Einstein",
                                                        max_width="100%",
                                                        max_height="100%",
                                                        object_fit="contain",
                                                        border_radius="0.5rem",
                                                    ),
                                                    display="flex",
                                                    height="10rem",
                                                    align_items="center",
                                                    justify_content="center",
                                                    width="10rem",
                                                ),
                                                rx.el.br(),
                                                rx.text.span(
                                                    "Albert Einstein",
                                                    font_size="0.75rem",
                                                    line_height="1rem",
                                                ),
                                                class_name="dark:border-purple-700",
                                                background_color="transparent",
                                                border_width="2px",
                                                border_color="#1E3A8A",
                                                border_style="solid",
                                                display="flex",
                                                flex_direction="column",
                                                align_items="center",
                                                justify_content="center",
                                                padding="0.75rem",
                                                border_radius="1rem",
                                            ),
                                            rx.el.button(
                                                rx.flex(
                                                    rx.image(
                                                        src="https://replicate.delivery/pbxt/ZtJM15tz4n6nGpZkZ2bi6yLTfi4MGE3emyLHAUXir1JoUlDTA/ComfyUI_00002_.png",
                                                        alt="Genghis Khan",
                                                        max_width="100%",
                                                        max_height="100%",
                                                        object_fit="contain",
                                                        border_radius="0.5rem",
                                                    ),
                                                    display="flex",
                                                    height="10rem",
                                                    align_items="center",
                                                    justify_content="center",
                                                    width="10rem",
                                                ),
                                                rx.el.br(),
                                                rx.text.span(
                                                    "Genghis Khan",
                                                    font_size="0.75rem",
                                                    line_height="1rem",
                                                ),
                                                class_name="dark:border-purple-700",
                                                background_color="transparent",
                                                border_width="2px",
                                                border_color="#1E3A8A",
                                                border_style="solid",
                                                display="flex",
                                                flex_direction="column",
                                                align_items="center",
                                                justify_content="center",
                                                padding="0.75rem",
                                                border_radius="1rem",
                                            ),
                                            rx.el.button(
                                                rx.flex(
                                                    rx.image(
                                                        src="https://replicate.delivery/pbxt/zxT3wXAdPE6rNJP1sfroJiTawHskstDIJyX2ufD4fXaw8LHmA/ComfyUI_00002_.png",
                                                        alt="Elon Musk",
                                                        max_width="100%",
                                                        max_height="100%",
                                                        object_fit="contain",
                                                        border_radius="0.5rem",
                                                    ),
                                                    display="flex",
                                                    height="10rem",
                                                    align_items="center",
                                                    justify_content="center",
                                                    width="10rem",
                                                ),
                                                rx.el.br(),
                                                rx.text.span(
                                                    "Elon Musk",
                                                    font_size="0.75rem",
                                                    line_height="1rem",
                                                ),
                                                class_name="dark:border-purple-700",
                                                background_color="transparent",
                                                border_width="2px",
                                                border_color="#1E3A8A",
                                                border_style="solid",
                                                display="flex",
                                                flex_direction="column",
                                                align_items="center",
                                                justify_content="center",
                                                padding="0.75rem",
                                                border_radius="1rem",
                                            ),
                                            rx.el.button(
                                                rx.flex(
                                                    rx.image(
                                                        src="https://i.ibb.co/4Mw6Htt/Jensen-Huang.png",
                                                        alt="Jensen Huang",
                                                        max_width="100%",
                                                        max_height="100%",
                                                        object_fit="contain",
                                                        border_radius="0.5rem",
                                                    ),
                                                    display="flex",
                                                    height="10rem",
                                                    align_items="center",
                                                    justify_content="center",
                                                    width="10rem",
                                                ),
                                                rx.el.br(),
                                                rx.text.span(
                                                    "Jensen Huang",
                                                    font_size="0.75rem",
                                                    line_height="1rem",
                                                ),
                                                class_name="dark:border-purple-700",
                                                background_color="transparent",
                                                border_width="2px",
                                                border_color="#1E3A8A",
                                                border_style="solid",
                                                display="flex",
                                                flex_direction="column",
                                                align_items="center",
                                                justify_content="center",
                                                padding="0.75rem",
                                                border_radius="1rem",
                                            ),
                                            rx.el.button(
                                                rx.flex(
                                                    rx.image(
                                                        src="https://replicate.delivery/pbxt/eN4pHz2D49XAYqPxnaFcZolYxGzEcdlmpBk5cen8Ib7fFMHmA/ComfyUI_00002_.png",
                                                        alt="Gordon Ramsay",
                                                        max_width="100%",
                                                        max_height="100%",
                                                        object_fit="contain",
                                                        border_radius="0.5rem",
                                                    ),
                                                    display="flex",
                                                    height="10rem",
                                                    align_items="center",
                                                    justify_content="center",
                                                    width="10rem",
                                                ),
                                                rx.el.br(),
                                                rx.text.span(
                                                    "Gordon Ramsay",
                                                    font_size="0.75rem",
                                                    line_height="1rem",
                                                ),
                                                class_name="dark:border-purple-700",
                                                background_color="transparent",
                                                border_width="2px",
                                                border_color="#1E3A8A",
                                                border_style="solid",
                                                display="flex",
                                                flex_direction="column",
                                                align_items="center",
                                                justify_content="center",
                                                padding="0.75rem",
                                                border_radius="1rem",
                                            ),
                                            rx.el.button(
                                                rx.flex(
                                                    rx.image(
                                                        src="https://i.ibb.co/hmY3sd8/pikaso-texttoimage-Cartoon-closeup-portrait-of-presidential-candidate-removebg-preview-transformed.png",
                                                        alt="Kamala Harris",
                                                        max_width="100%",
                                                        max_height="100%",
                                                        object_fit="contain",
                                                        border_radius="0.5rem",
                                                    ),
                                                    display="flex",
                                                    height="10rem",
                                                    align_items="center",
                                                    justify_content="center",
                                                    width="10rem",
                                                ),
                                                rx.el.br(),
                                                rx.text.span(
                                                    "Kamala Harris",
                                                    font_size="0.75rem",
                                                    line_height="1rem",
                                                ),
                                                class_name="dark:border-purple-700",
                                                background_color="transparent",
                                                border_width="2px",
                                                border_color="#1E3A8A",
                                                border_style="solid",
                                                display="flex",
                                                flex_direction="column",
                                                align_items="center",
                                                justify_content="center",
                                                padding="0.75rem",
                                                border_radius="1rem",
                                            ),
                                            rx.el.button(
                                                rx.flex(
                                                    rx.image(
                                                        src="https://replicate.delivery/pbxt/EwtmumDFmBoxMB6vF207UslR2vZmHoLUPnWffBkizfGXYPHmA/ComfyUI_00002_.png",
                                                        alt="Donald Trump",
                                                        max_width="100%",
                                                        max_height="100%",
                                                        object_fit="contain",
                                                        border_radius="0.5rem",
                                                    ),
                                                    display="flex",
                                                    height="10rem",
                                                    align_items="center",
                                                    justify_content="center",
                                                    width="10rem",
                                                ),
                                                rx.el.br(),
                                                rx.text.span(
                                                    "Donald Trump",
                                                    font_size="0.75rem",
                                                    line_height="1rem",
                                                ),
                                                class_name="dark:border-purple-700",
                                                background_color="transparent",
                                                border_width="2px",
                                                border_color="#1E3A8A",
                                                border_style="solid",
                                                display="flex",
                                                flex_direction="column",
                                                align_items="center",
                                                justify_content="center",
                                                padding="0.75rem",
                                                border_radius="1rem",
                                            ),
                                            rx.el.button(
                                                rx.flex(
                                                    rx.image(
                                                        src="https://i.ibb.co/PTHQ7Qn/modi-indianprimeminister-removebg.png",
                                                        alt="Narendra Modi",
                                                        max_width="100%",
                                                        max_height="100%",
                                                        object_fit="contain",
                                                        border_radius="0.5rem",
                                                    ),
                                                    display="flex",
                                                    height="10rem",
                                                    align_items="center",
                                                    justify_content="center",
                                                    width="10rem",
                                                ),
                                                rx.el.br(),
                                                rx.text.span(
                                                    "Narendra Modi",
                                                    font_size="0.75rem",
                                                    line_height="1rem",
                                                ),
                                                class_name="dark:border-purple-700",
                                                background_color="transparent",
                                                border_width="2px",
                                                border_color="#1E3A8A",
                                                border_style="solid",
                                                display="flex",
                                                flex_direction="column",
                                                align_items="center",
                                                justify_content="center",
                                                padding="0.75rem",
                                                border_radius="1rem",
                                            ),
                                            rx.el.button(
                                                rx.flex(
                                                    rx.image(
                                                        src="https://i.ibb.co/qymPbXp/Angela-Markel.png",
                                                        alt="Angela Markel",
                                                        max_width="100%",
                                                        max_height="100%",
                                                        object_fit="contain",
                                                        border_radius="0.5rem",
                                                    ),
                                                    display="flex",
                                                    height="10rem",
                                                    align_items="center",
                                                    justify_content="center",
                                                    width="10rem",
                                                ),
                                                rx.el.br(),
                                                rx.text.span(
                                                    "Angela Markel",
                                                    font_size="0.75rem",
                                                    line_height="1rem",
                                                ),
                                                class_name="dark:border-purple-700",
                                                background_color="transparent",
                                                border_width="2px",
                                                border_color="#1E3A8A",
                                                border_style="solid",
                                                display="flex",
                                                flex_direction="column",
                                                align_items="center",
                                                justify_content="center",
                                                padding="0.75rem",
                                                border_radius="1rem",
                                            ),
                                            rx.el.button(
                                                rx.flex(
                                                    rx.image(
                                                        src="https://i.ibb.co/wJR6HTJ/Megan-Thee-Stallion.png",
                                                        alt="Megan Jovon Ruth Pete (Megan Thee Stallion)",
                                                        max_width="100%",
                                                        max_height="100%",
                                                        object_fit="contain",
                                                        border_radius="0.5rem",
                                                    ),
                                                    display="flex",
                                                    height="10rem",
                                                    align_items="center",
                                                    justify_content="center",
                                                    width="10rem",
                                                ),
                                                rx.el.br(),
                                                rx.text.span(
                                                    "Megan Jovon Ruth Pete (Megan Thee Stallion)",
                                                    font_size="0.75rem",
                                                    line_height="1rem",
                                                ),
                                                class_name="dark:border-purple-700",
                                                background_color="transparent",
                                                border_width="2px",
                                                border_color="#1E3A8A",
                                                border_style="solid",
                                                display="flex",
                                                flex_direction="column",
                                                align_items="center",
                                                justify_content="center",
                                                padding="0.75rem",
                                                border_radius="1rem",
                                            ),
                                            rx.el.button(
                                                rx.flex(
                                                    rx.image(
                                                        src="https://i.ibb.co/p0mydmw/Neil-Tyson.png",
                                                        alt="Neil deGrasse Tyson",
                                                        max_width="100%",
                                                        max_height="100%",
                                                        object_fit="contain",
                                                        border_radius="0.5rem",
                                                    ),
                                                    display="flex",
                                                    height="10rem",
                                                    align_items="center",
                                                    justify_content="center",
                                                    width="10rem",
                                                ),
                                                rx.el.br(),
                                                rx.text.span(
                                                    "Neil deGrasse Tyson",
                                                    font_size="0.75rem",
                                                    line_height="1rem",
                                                ),
                                                class_name="dark:border-purple-700",
                                                background_color="transparent",
                                                border_width="2px",
                                                border_color="#1E3A8A",
                                                border_style="solid",
                                                display="flex",
                                                flex_direction="column",
                                                align_items="center",
                                                justify_content="center",
                                                padding="0.75rem",
                                                border_radius="1rem",
                                            ),
                                            gap="2rem",
                                            display="grid",
                                            grid_template_columns="repeat(3, minmax(0, 1fr))",
                                        ),
                                        rx.heading(
                                            "Custom Participant",
                                            font_weight="700",
                                            margin_bottom="1rem",
                                            margin_top="2rem",
                                            font_size="1.25rem",
                                            line_height="1.75rem",
                                            as_="h2",
                                        ),
                                        rx.flex(
                                            rx.el.button(
                                                rx.flex(
                                                    rx.image(
                                                        src="https://www.shutterstock.com/image-vector/user-profile-icon-vector-avatar-600nw-2220431045.jpg",
                                                        alt="Custom",
                                                        max_width="100%",
                                                        max_height="100%",
                                                        object_fit="contain",
                                                        border_radius="0.5rem",
                                                    ),
                                                    display="flex",
                                                    height="10rem",
                                                    align_items="center",
                                                    justify_content="center",
                                                    width="10rem",
                                                ),
                                                rx.el.br(),
                                                rx.text.span(
                                                    "Custom Character",
                                                    font_size="0.75rem",
                                                    line_height="1rem",
                                                ),
                                                class_name="dark:border-purple-700",
                                                background_color="transparent",
                                                border_width="2px",
                                                border_color="#1E3A8A",
                                                border_style="solid",
                                                display="flex",
                                                flex_direction="column",
                                                align_items="center",
                                                justify_content="center",
                                                padding="0.75rem",
                                                border_radius="1rem",
                                            ),
                                            display="flex",
                                            flex_direction="column",
                                            align_items="center",
                                            margin_bottom="2rem",
                                        ),
                                        rx.box(
                                            rx.heading(
                                                "Number of Rounds",
                                                font_weight="600",
                                                margin_bottom="0.5rem",
                                                font_size="1.125rem",
                                                line_height="1.75rem",
                                                as_="h2",
                                            ),
                                            rx.el.select(
                                                rx.el.option(
                                                    "5",
                                                    value="5",
                                                    background_color="hsl(245, 20%, 20%)",
                                                    color="hsl(245, 30%, 90%)",
                                                ),
                                                rx.el.option(
                                                    "10",
                                                    value="10",
                                                    selected=True,
                                                    background_color="hsl(245, 20%, 20%)",
                                                    color="hsl(245, 30%, 90%)",
                                                ),
                                                rx.el.option(
                                                    "50",
                                                    value="50",
                                                    background_color="hsl(245, 20%, 20%)",
                                                    color="hsl(245, 30%, 90%)",
                                                ),
                                                rx.el.option(
                                                    "100",
                                                    value="100",
                                                    background_color="hsl(245, 20%, 20%)",
                                                    color="hsl(245, 30%, 90%)",
                                                ),
                                                rx.el.option(
                                                    "200",
                                                    value="200",
                                                    background_color="hsl(245, 20%, 20%)",
                                                    color="hsl(245, 30%, 90%)",
                                                ),
                                                color="#ffffff",
                                                background_color="hsl(245, 20%, 20%)",
                                                border_width="1px",
                                                border_color="#6B7280",
                                                _focus={
                                                    "outline-style": "none",
                                                    "box-shadow": "var(--tw-ring-inset) 0 0 0 calc(2px + var(--tw-ring-offset-width)) var(--tw-ring-color)",
                                                    "--ring-color": "#8B5CF6",
                                                },
                                                padding_left="0.75rem",
                                                padding_right="0.75rem",
                                                padding_top="0.5rem",
                                                padding_bottom="0.5rem",
                                                border_radius="0.25rem",
                                            ),
                                            margin_top="1rem",
                                        ),
                                        text_align="center",
                                    ),
                                    rx.box(
                                        rx.heading(
                                            "Choose your topic",
                                            font_size="1.25rem",
                                            line_height="1.75rem",
                                            as_="h2",
                                        ),
                                        rx.el.input(
                                            class_name="bg-background border-border placeholder-gray-500 text-foreground",
                                            placeholder="Enter an interesting topic",
                                            value=True,
                                            border_bottom_width="1px",
                                            _focus={
                                                "border-bottom-width": "2px",
                                                "outline-style": "none",
                                            },
                                            margin_top="0.5rem",
                                            padding_left="1rem",
                                            padding_right="1rem",
                                            padding_top="0.5rem",
                                            padding_bottom="0.5rem",
                                            font_size="1.125rem",
                                            line_height="1.75rem",
                                        ),
                                        margin_bottom="2rem",
                                        margin_top="2rem",
                                        text_align="center",
                                    ),
                                    rx.box(
                                        rx.heading(
                                            "Select Musical Style",
                                            font_size="1.25rem",
                                            line_height="1.75rem",
                                            as_="h2",
                                        ),
                                        rx.el.select(
                                            rx.el.option(
                                                "None", value="None", selected=True
                                            ),
                                            rx.el.option("Ambient", value="Ambient"),
                                            rx.el.option("Classical", value="Classical"),
                                            rx.el.option("Cinematic", value="Cinematic"),
                                            rx.el.option("Electronic", value="Electronic"),
                                            rx.el.option("Folk", value="Folk"),
                                            rx.el.option("Funk", value="Funk"),
                                            rx.el.option("Hip-Hop", value="Hip-Hop"),
                                            rx.el.option("Jazz", value="Jazz"),
                                            rx.el.option("Pop", value="Pop"),
                                            rx.el.option("Rock", value="Rock"),
                                            rx.el.option("Soul", value="Soul"),
                                            rx.el.option("Blues", value="Blues"),
                                            rx.el.option("Country", value="Country"),
                                            rx.el.option("Reggae", value="Reggae"),
                                            rx.el.option("Latin", value="Latin"),
                                            rx.el.option("Metal", value="Metal"),
                                            rx.el.option("Dance", value="Dance"),
                                            rx.el.option("Chill", value="Chill"),
                                            rx.el.option("Acoustic", value="Acoustic"),
                                            rx.el.option(
                                                "Instrumental", value="Instrumental"
                                            ),
                                            rx.el.option("Lo-fi", value="Lo-fi"),
                                            rx.el.option("Happy", value="Happy"),
                                            rx.el.option("Sad", value="Sad"),
                                            rx.el.option("Relaxing", value="Relaxing"),
                                            rx.el.option("Upbeat", value="Upbeat"),
                                            rx.el.option(
                                                "Motivational", value="Motivational"
                                            ),
                                            rx.el.option("Funny", value="Funny"),
                                            rx.el.option("Dramatic", value="Dramatic"),
                                            rx.el.option("Romantic", value="Romantic"),
                                            rx.el.option("Horror", value="Horror"),
                                            rx.el.option("Epic", value="Epic"),
                                            rx.el.option("Corporate", value="Corporate"),
                                            rx.el.option("Kids", value="Kids"),
                                            rx.el.option("Holiday", value="Holiday"),
                                            rx.el.option(
                                                "Sound Effects", value="Sound Effects"
                                            ),
                                            rx.el.option("Nature", value="Nature"),
                                            rx.el.option("Space", value="Space"),
                                            rx.el.option("Sci-fi", value="Sci-fi"),
                                            rx.el.option("Fantasy", value="Fantasy"),
                                            rx.el.option("Historical", value="Historical"),
                                            rx.el.option("Adventure", value="Adventure"),
                                            rx.el.option("Action", value="Action"),
                                            rx.el.option("Mystery", value="Mystery"),
                                            rx.el.option("Suspense", value="Suspense"),
                                            rx.el.option("Thriller", value="Thriller"),
                                            rx.el.option("Comedy", value="Comedy"),
                                            rx.el.option(
                                                "Documentary", value="Documentary"
                                            ),
                                            rx.el.option("Travel", value="Travel"),
                                            rx.el.option("Sports", value="Sports"),
                                            rx.el.option("News", value="News"),
                                            rx.el.option("Games", value="Games"),
                                            rx.el.option("Workout", value="Workout"),
                                            rx.el.option("Meditation", value="Meditation"),
                                            rx.el.option("Study", value="Study"),
                                            rx.el.option("Sleep", value="Sleep"),
                                            rx.el.option("Background", value="Background"),
                                            rx.el.option("Wedding", value="Wedding"),
                                            rx.el.option("Party", value="Party"),
                                            class_name="Landing_styledSelect__4Y9UM",
                                            margin_top="0.5rem",
                                        ),
                                        margin_bottom="2rem",
                                        margin_top="2rem",
                                        text_align="center",
                                    ),
                                    rx.el.button(
                                        "Compose Podcast",
                                        class_name="Landing_buttonPrimary__Xl89G Landing_cursorPointer__tarKk",
                                        margin_bottom="1rem",
                                        position="relative",
                                    ),
                                    rx.flex(
                                        rx.divider(
                                            border_color="#D1D5DB",
                                            border_top_width="1px",
                                            flex_grow="1",
                                        ),
                                        rx.text.span(
                                            "or",
                                            margin_left="0.5rem",
                                            margin_right="0.5rem",
                                            color="#6B7280",
                                        ),
                                        rx.divider(
                                            border_color="#D1D5DB",
                                            border_top_width="1px",
                                            flex_grow="1",
                                        ),
                                        display="flex",
                                        align_items="center",
                                        margin_top="1rem",
                                        margin_bottom="1rem",
                                    ),
                                    rx.box(
                                        rx.el.button(
                                            "Show Sample Podcast",
                                            background_color="#6D28D9",
                                            font_weight="600",
                                            _hover={"background-color": "#8B5CF6"},
                                            padding_left="1rem",
                                            padding_right="1rem",
                                            padding_top="0.5rem",
                                            padding_bottom="0.5rem",
                                            border_radius="0.25rem",
                                            color="#ffffff",
                                        ),
                                        margin_top="1rem",
                                    ),
                                    max_width="768px",
                                    margin_left="auto",
                                    margin_right="auto",
                                    padding="1rem",
                                    text_align="center",
                                ),
                                class_name="bg-gradient-to-b from-slate-900 to-purple-900/30",
                                display="flex",
                                flex_direction="column",
                                flex_grow="1",
                                align_items="center",
                                justify_content="center",
                                padding_left=rx.breakpoints(
                                    {"0px": "1rem", "768px": "6rem"}
                                ),
                                padding_right=rx.breakpoints(
                                    {"0px": "1rem", "768px": "6rem"}
                                ),
                                padding_top=rx.breakpoints(
                                    {"0px": "1.5rem", "768px": "3rem"}
                                ),
                                padding_bottom=rx.breakpoints(
                                    {"0px": "1.5rem", "768px": "3rem"}
                                ),
                                color="#ffffff",
                            ),
                            rx.box(margin_top="2rem"),
                            display="flex",
                            flex_direction="column",
                            justify_content="space-between",
                            min_height="100vh",
                        ),
                        class_name="bg-gradient-to-b from-slate-900 to-purple-900",
                        flex_grow="1",
                    ),
                    rx.el.template(
                        custom_attrs={"data-dgst": "BAILOUT_TO_CLIENT_SIDE_RENDERING"}
                    ),
                    display="flex",
                    flex_direction="column",
                    min_height="100vh",
                ),
                custom_attrs={"data-overlay-container": "true"},
            ),
            rx.script(
                src="/_next/static/chunks/webpack-cc0e97d36042a1cd.js",
                strategy="afterInteractive",
            ),
            rx.script(
                """(self.__next_f=self.__next_f||[]).push([0]);self.__next_f.push([2,null])"""
            ),
            rx.script(
                """self.__next_f.push([1,"1:HL[\"/_next/static/media/a34f9d1faa5f3315-s.p.woff2\",\"font\",{\"crossOrigin\":\"\",\"type\":\"font/woff2\"}]\n2:HL[\"/_next/static/css/628765f20b848f76.css\",\"style\"]\n3:HL[\"/_next/static/css/50eff5b5a304083f.css\",\"style\"]\n"])"""
            ),
            rx.script(
                """self.__next_f.push([1,"4:I[5751,[],\"\"]\n6:I[6513,[],\"ClientPageRoot\"]\n7:I[9813,[\"699\",\"static/chunks/8e1d74a4-44c6c3343a88bc09.js\",\"740\",\"static/chunks/740-c96163b104825a35.js\",\"931\",\"static/chunks/app/page-4ac0b61589c3b625.js\"],\"default\",1]\n8:I[8835,[\"67\",\"static/chunks/aa7babf8-d144d7c22dac3895.js\",\"699\",\"static/chunks/8e1d74a4-44c6c3343a88bc09.js\",\"644\",\"static/chunks/644-a8d8bdbd19f2f51f.js\",\"138\",\"static/chunks/138-632539dc9da923bc.js\",\"444\",\"static/chunks/444-6f20abd6757d460c.js\",\"185\",\"static/chunks/app/layout-fc81a75f4f9d4044.js\"],\"default\"]\n9:\"$Sreact.suspense\"\na:I[912,[\"67\",\"static/chunks/aa7babf8-d144d7c22dac3895.js\",\"699\",\"static/chunks/8e1d74a4-44c6c3343a88bc09.js\",\"644\",\"static/chunks/644-a8d8bdbd19f2f51f.js\",\"138\",\"static/chunks/138-632539dc9da923bc.js\",\"444\",\"static/chunks/444-6f20abd6757d460c.js\",\"185\",\"static/chunks/app/layout-fc81a75f4f9d4044.js\"],\"BailoutToCSR\"]\nb:I[2642,[\"67\",\"static/chunks/aa7babf8-d144d7c22dac3895.js\",\"699\",\"static/chunks/8e1d74a4-44c6c3343a88bc09.js\",\"644\",\"static/chunks/644-a8d8bdbd19f2f51f.js\",\"138\",\"static/chunks/138-632539dc9da923bc.js\",\"444\",\"static/chunks/444-6f20abd6757d460c.js\",\"185\",\"static/chunks/app/layout-fc81a75f4f9d4044.js\"],\"default\"]\nc:I[9275,[],\"\"]\nd:I[1343,[],\"\"]\ne:I[9187,[\"67\",\"static/chunks/aa7babf8-d144d7c22dac3895.js\",\"699\",\"static/chunks/8e1d74a4-44c6c3343a88bc09.js\",\"644\",\"static/chunks/644-a8d8bdbd19f2f51f.js\",\"138\",\"static/chunks/138-632539dc9da923bc.js\",\"444\",\"static/chunks/444-6f20abd6757d460c.js\",\"185\",\"static/chunks/app/layout-fc81a75f4f9d4044.js\"],\"default\"]\n10:I[6130,[],\"\"]\n11:[]\n"])"""
            ),
            rx.script(
                """self.__next_f.push([1,"0:[\"$\",\"$L4\",null,{\"buildId\":\"eKh7i_CpS3h-9yyxGrbEP\",\"assetPrefix\":\"\",\"urlParts\":[\"\",\"\"],\"initialTree\":[\"\",{\"children\":[\"__PAGE__\",{}]},\"$undefined\",\"$undefined\",true],\"initialSeedData\":[\"\",{\"children\":[\"__PAGE__\",{},[[\"$L5\",[\"$\",\"$L6\",null,{\"props\":{\"params\":{},\"searchParams\":{}},\"Component\":\"$7\"}],null],null],null]},[[[[\"$\",\"link\",\"0\",{\"rel\":\"stylesheet\",\"href\":\"/_next/static/css/628765f20b848f76.css\",\"precedence\":\"next\",\"crossOrigin\":\"$undefined\"}],[\"$\",\"link\",\"1\",{\"rel\":\"stylesheet\",\"href\":\"/_next/static/css/50eff5b5a304083f.css\",\"precedence\":\"next\",\"crossOrigin\":\"$undefined\"}]],[\"$\",\"html\",null,{\"lang\":\"en\",\"className\":\"__className_36bd41\",\"style\":{\"backgroundColor\":\"inherit\"},\"children\":[\"$\",\"body\",null,{\"style\":{\"margin\":0,\"padding\":0},\"children\":[\"$\",\"$L8\",null,{\"children\":[\"$\",\"div\",null,{\"className\":\"flex flex-col min-h-screen\",\"children\":[[\"$\",\"$9\",null,{\"fallback\":null,\"children\":[\"$\",\"$La\",null,{\"reason\":\"next/dynamic\",\"children\":[\"$\",\"$Lb\",null,{}]}]}],[\"$\",\"main\",null,{\"className\":\"flex-grow bg-gradient-to-b from-slate-900 to-purple-900\",\"children\":[\"$\",\"$Lc\",null,{\"parallelRouterKey\":\"children\",\"segmentPath\":[\"children\"],\"error\":\"$undefined\",\"errorStyles\":\"$undefined\",\"errorScripts\":\"$undefined\",\"template\":[\"$\",\"$Ld\",null,{}],\"templateStyles\":\"$undefined\",\"templateScripts\":\"$undefined\",\"notFound\":[[\"$\",\"title\",null,{\"children\":\"404: This page could not be found.\"}],[\"$\",\"div\",null,{\"style\":{\"fontFamily\":\"system-ui,\\\"Segoe UI\\\",Roboto,Helvetica,Arial,sans-serif,\\\"Apple Color Emoji\\\",\\\"Segoe UI Emoji\\\"\",\"height\":\"100vh\",\"textAlign\":\"center\",\"display\":\"flex\",\"flexDirection\":\"column\",\"alignItems\":\"center\",\"justifyContent\":\"center\"},\"children\":[\"$\",\"div\",null,{\"children\":[[\"$\",\"style\",null,{\"dangerouslySetInnerHTML\":{\"__html\":\"body{color:#000;background:#fff;margin:0}.next-error-h1{border-right:1px solid rgba(0,0,0,.3)}@media (prefers-color-scheme:dark){body{color:#fff;background:#000}.next-error-h1{border-right:1px solid rgba(255,255,255,.3)}}\"}}],[\"$\",\"h1\",null,{\"className\":\"next-error-h1\",\"style\":{\"display\":\"inline-block\",\"margin\":\"0 20px 0 0\",\"padding\":\"0 23px 0 0\",\"fontSize\":24,\"fontWeight\":500,\"verticalAlign\":\"top\",\"lineHeight\":\"49px\"},\"children\":\"404\"}],[\"$\",\"div\",null,{\"style\":{\"display\":\"inline-block\"},\"children\":[\"$\",\"h2\",null,{\"style\":{\"fontSize\":14,\"fontWeight\":400,\"lineHeight\":\"49px\",\"margin\":0},\"children\":\"This page could not be found.\"}]}]]}]}]],\"notFoundStyles\":[]}]}],[\"$\",\"$9\",null,{\"fallback\":null,\"children\":[\"$\",\"$La\",null,{\"reason\":\"next/dynamic\",\"children\":[\"$\",\"$Le\",null,{}]}]}]]}]}]}]}]],null],null],\"couldBeIntercepted\":false,\"initialHead\":[null,\"$Lf\"],\"globalErrorComponent\":\"$10\",\"missingSlots\":\"$W11\"}]\n"])"""
            ),
            rx.script(
                """self.__next_f.push([1,"f:[[\"$\",\"meta\",\"0\",{\"name\":\"viewport\",\"content\":\"width=device-width, initial-scale=1\"}],[\"$\",\"meta\",\"1\",{\"charSet\":\"utf-8\"}],[\"$\",\"title\",\"2\",{\"children\":\"FiCast: Knowledgeable Music in Your Ears\"}],[\"$\",\"meta\",\"3\",{\"name\":\"description\",\"content\":\"FiCast is a content delivery system that augments our ideation \u0026 learning with thoughtful conversations between agentic models that LLM imagines them to be.\"}],[\"$\",\"link\",\"4\",{\"rel\":\"icon\",\"href\":\"/favicon.ico\"}],[\"$\",\"meta\",\"5\",{\"name\":\"next-size-adjust\"}]]\n5:null\n"])"""
            ),
            margin="0",
            padding="0",
        ),
    )
