defaults:
  - base  # Inherit from base.yaml
  - characters: default
  - speech: default
  
podcast_config:
  topic: "Democracy"
  n_rounds: ${conversation_config.n_rounds}  # Inherit from base.yaml
  character_cfg:
    hosts: ${characters.hosts}  # Reference to host in characters.yaml
    guests: ${characters.guests}  # Reference to guests in characters.yaml
  speech: ${speech}
  

